name: Quality gate

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        default: "3.11"
        type: string

jobs:
  quality-gate:
    name: quality-gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
      - run: python -m pip install --upgrade pip
      - name: Install quality-gate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python -m pip install "quality-gate[tools] @ git+https://x-access-token:${GITHUB_TOKEN}@github.com/TheTraitor0FJesus/quality-gate.git@main"
      - run: quality-gate install-dependencies
      - run: quality-gate check
